# Generated by Django 2.2.9 on 2020-01-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.TextField(default='0000')),
                ('name', models.TextField(default='name')),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
